<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="2" ignored="0" total="4" passed="2">
  <reporter-output>
  </reporter-output>
  <suite name="nEXCITIZEN" duration-ms="152154" started-at="2019-12-17T10:25:05Z" finished-at="2019-12-17T10:27:38Z">
    <groups>
    </groups>
    <test name="nEXCITIZEN_TestCase1" duration-ms="152154" started-at="2019-12-17T10:25:05Z" finished-at="2019-12-17T10:27:38Z">
      <class name="com.TestCase.EmailTestCase_Folder.SendEmail_TestCase">
        <test-method status="PASS" signature="EmailSend_Message()[pri:37, instance:com.TestCase.EmailTestCase_Folder.SendEmail_TestCase@6f1fba17]" name="EmailSend_Message" duration-ms="5366" started-at="2019-12-17T10:27:32Z" finished-at="2019-12-17T10:27:38Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- EmailSend_Message -->
      </class> <!-- com.TestCase.EmailTestCase_Folder.SendEmail_TestCase -->
      <class name="com.TestCase.RegistrationandLoginTestCase_Folder.Login_TestCase">
        <test-method status="PASS" signature="Url_login()[pri:0, instance:com.TestCase.RegistrationandLoginTestCase_Folder.Login_TestCase@6c3708b3]" name="Url_login" is-config="true" duration-ms="20657" started-at="2019-12-17T10:25:05Z" finished-at="2019-12-17T10:25:26Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Url_login -->
        <test-method status="FAIL" signature="Without_Username()[pri:1, instance:com.TestCase.RegistrationandLoginTestCase_Folder.Login_TestCase@6c3708b3]" name="Without_Username" duration-ms="62247" started-at="2019-12-17T10:25:26Z" finished-at="2019-12-17T10:26:28Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Login Successful without username] but found [Login not successful without username]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Login Successful without username] but found [Login not successful without username]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at com.PageObject.New_Registration.Login_Page.OnlyPassWordtest(Login_Page.java:55)
at com.TestCase.RegistrationandLoginTestCase_Folder.Login_TestCase.Without_Username(Login_TestCase.java:17)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:73)
at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:123)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Without_Username -->
        <test-method status="FAIL" signature="Without_Password()[pri:2, instance:com.TestCase.RegistrationandLoginTestCase_Folder.Login_TestCase@6c3708b3]" name="Without_Password" duration-ms="62152" started-at="2019-12-17T10:26:28Z" finished-at="2019-12-17T10:27:30Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Login Successful without Password] but found [Login not successful without Password]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Login Successful without Password] but found [Login not successful without Password]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at com.PageObject.New_Registration.Login_Page.OnlyUserNametest(Login_Page.java:86)
at com.TestCase.RegistrationandLoginTestCase_Folder.Login_TestCase.Without_Password(Login_TestCase.java:21)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:73)
at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:123)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Without_Password -->
        <test-method status="PASS" signature="Orginal_user_pass()[pri:3, instance:com.TestCase.RegistrationandLoginTestCase_Folder.Login_TestCase@6c3708b3]" name="Orginal_user_pass" duration-ms="1698" started-at="2019-12-17T10:27:30Z" finished-at="2019-12-17T10:27:32Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Orginal_user_pass -->
      </class> <!-- com.TestCase.RegistrationandLoginTestCase_Folder.Login_TestCase -->
    </test> <!-- nEXCITIZEN_TestCase1 -->
  </suite> <!-- nEXCITIZEN -->
</testng-results>
